import matplotlib.pyplot as plt
import numpy as np
import os

if __name__ == "__main__":
    plt.rc('text', usetex=True)
    n = range(18)
    s1_true = np.loadtxt(os.path.join("data", "1st_s18.txt"))
    s2_true = np.loadtxt(os.path.join("data", "2nd_s18.txt"))
    s1_calc = np.loadtxt("1st_result_s18.txt")
    s2_calc = np.loadtxt("2nd_result_s18.txt")

    _, axis = plt.subplots(2)
    range_inf = range(1, 19)
    axis[0].plot(range_inf, [(abs(s1_calc[i][0] - s1_true[i])) for i in n], label=r'$|s_k - \underline{\mathbf{s_k}}|$')
    axis[0].plot(range_inf, [(abs(s1_calc[i][1] - s1_true[i])) for i in n], label=r'$|s_k - \overline{\mathbf{s_k}}|$')
    axis[0].set_xticks(range_inf)
    axis[0].set_title('$k=1,2,...,18$')
    axis[0].legend()
    range_sup = range(19, 37)
    axis[1].plot(range_sup, [(abs(s2_calc[i][0] - s2_true[i])) for i in n], label=r'$|s_k - \underline{\mathbf{s_k}}|$')
    axis[1].plot(range_sup, [(abs(s2_calc[i][1] - s2_true[i])) for i in n], label=r'$|s_k - \overline{\mathbf{s_k}}|$')
    axis[1].set_xticks(range_sup)
    axis[1].set_title('$k=19,20,...,36$')
    axis[1].legend()
    plt.tight_layout()
    plt.show()

    # _, axis = plt.subplots(2)
    # range_inf = range(1, 19)
    # axis[0].plot(range_inf, [s1_true[i] for i in n], label=r'$s_k$')
    # axis[0].plot(range_inf, [s1_calc[i][0] for i in n], label=r'$\underline{\mathbf{s_k}}$')
    # axis[0].plot(range_inf, [s1_calc[i][1] for i in n], label=r'$\overline{\mathbf{s_k}}$')
    # axis[0].set_xticks(range_inf)
    # axis[0].set_title('$k=1,2,...,18$')
    # axis[0].legend()
    # range_sup = range(19, 37)
    # axis[1].plot(range_sup, [s2_true[i] for i in n], label=r'$s_k$')
    # axis[1].plot(range_sup, [s2_calc[i][0] for i in n], label=r'$\underline{\mathbf{s_k}}$')
    # axis[1].plot(range_sup, [s2_calc[i][1] for i in n], label=r'$\overline{\mathbf{s_k}}$')
    # axis[1].set_xticks(range_sup)
    # axis[1].set_title('$k=19,20,...,36$')
    # axis[1].legend()
    # plt.tight_layout()
    # plt.show()
